/**
 * Suggestions while you type in a settings file — keys, and the values a key
 * accepts.
 *
 * **The editor's own mechanism, not a control of ours.** This started as an
 * inline `<select>` widget parked at the end of the line, which was a UI
 * invented for a problem editors already solve: you type, a list appears, you
 * pick. Autocompletion is what a person reaches for in any other file, it costs
 * no screen space when you are only reading, and it does not need a click.
 *
 * **A suggestion is not a closed set, which is why `maxCommittedFileBytes` is
 * here and had no menu.** A dropdown claims these are the only legal values; a
 * completion list says "here are the useful ones" and lets you type 7340032
 * anyway. The setting takes any positive number and the pane offers four sizes,
 * so offering those four as suggestions is exactly right.
 *
 * **Line matching, not the YAML syntax tree.** These files are generated by
 * `writeSettingsText`, so their shape is known, and a half-typed line is not
 * valid YAML anyway — which is the moment completion has to work.
 */
import type { Completion, CompletionContext, CompletionResult } from '@codemirror/autocomplete'
import { holiCompletion } from './completion'
import type { Extension } from '@codemirror/state'
import { SETTINGS_FILE, SETTINGS_LOCAL_FILE, VAULT_SETTINGS } from '@holi/shared'
import type { SettingTarget, VaultSetting } from '@holi/shared'

/** Which settings file a path is, or `null` for anything else. A key called
 *  `landing` in somebody's own note is not a setting. */
function targetFor(path: string): SettingTarget | null {
  if (path === SETTINGS_FILE) return 'committed'
  if (path === SETTINGS_LOCAL_FILE) return 'local'
  return null
}

/** `dailyNotes: tr` → the key and what has been typed of the value. `null` when
 *  the cursor is not after a `key:` on this line. */
const VALUE_POSITION = /^(\s*)(?:#\s*)?([A-Za-z][A-Za-z0-9-]*):[ \t]*(.*)$/

/** `  dail` → an unfinished key. Also matches inside a comment, so uncommenting
 *  a line and retyping it still completes. */
const KEY_POSITION = /^(\s*)(?:#\s*)?([A-Za-z][A-Za-z0-9-]*)?$/

/** The flag switches under `hooks`, as their own completable keys. They are not
 *  in `VAULT_SETTINGS` by name — they live inside the `hooks` setting's type. */
function flagKeys(): { key: string; explanation: string }[] {
  const hooks = VAULT_SETTINGS.find((s) => s.type.kind === 'flags')
  if (hooks === undefined || hooks.type.kind !== 'flags') return []
  return hooks.type.flags.map((f) => ({ key: f.key, explanation: f.explanation }))
}

const BOOLEANS: Completion[] = [
  { label: 'true', type: 'keyword' },
  { label: 'false', type: 'keyword' },
]

/** A value, written the way it goes in a file: `{ kind: daily }`, not the label
 *  the settings pane shows. */
function literal(value: unknown): string {
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return `{ ${Object.entries(value)
      .map(([k, v]) => `${k}: ${String(v)}`)
      .join(', ')} }`
  }
  return String(value)
}

/** What the key on this line will accept. */
function valuesFor(key: string): Completion[] | null {
  const setting = VAULT_SETTINGS.find((s) => s.key === key)
  if (setting === undefined) {
    // A `hooks` flag: its own line, its own true/false.
    return flagKeys().some((f) => f.key === key) ? BOOLEANS : null
  }
  const type = setting.type
  if (type.kind === 'boolean') return BOOLEANS
  if (type.kind === 'flags') return null
  return type.options.map((option) => ({
    label: literal(option.value),
    // The pane's wording, as the note beside the value — so the file and the
    // tab explain a choice in the same words.
    detail: option.label,
    info: option.hint,
    type: 'constant',
  }))
}

/** The settings this file may carry, as completable keys. */
function keysFor(target: SettingTarget): Completion[] {
  const own = VAULT_SETTINGS.filter((s: VaultSetting) => s.target === target).map((s) => ({
    label: s.key,
    detail: s.label,
    info: s.explanation,
    type: 'property',
    apply: `${s.key}: `,
  }))
  return [
    ...own,
    ...flagKeys().map((f) => ({
      label: f.key,
      detail: f.explanation,
      type: 'property',
      apply: `${f.key}: `,
    })),
  ]
}

function source(target: SettingTarget) {
  return (context: CompletionContext): CompletionResult | null => {
    const line = context.state.doc.lineAt(context.pos)
    const before = line.text.slice(0, context.pos - line.from)

    const value = VALUE_POSITION.exec(before)
    if (value !== null) {
      const options = valuesFor(value[2]!)
      if (options === null) return null
      return {
        from: context.pos - value[3]!.length,
        options,
        // Without this, a list that has been filtered to nothing stays closed
        // when you delete back to the colon — the one moment you most want it.
        validFor: /^[^\s].*$/,
      }
    }

    const key = KEY_POSITION.exec(before)
    if (key === null) return null
    const typed = key[2] ?? ''
    // An empty line only completes when asked (⌃Space), so opening a file does
    // not greet you with a list you did not ask for.
    if (typed === '' && !context.explicit) return null
    return { from: context.pos - typed.length, options: keysFor(target), validFor: /^\w*$/ }
  }
}

/** Completion for `.holi/settings/app.yaml` and its local sibling; nothing for
 *  anything else. */
export function settingsCompletion(path: string): Extension[] {
  const target = targetFor(path)
  if (target === null) return []
  return [holiCompletion([source(target)])]
}

/** The source alone, for tests — a `CompletionContext` is cheaper to build than
 *  an editor, and what it returns is the whole behaviour. */
export const settingsCompletionSource = source
