/**
 * `holi` — the command the agent types to ask Holi to do something.
 *
 * A generated shell script rather than a shipped binary, for the reasons
 * `holi-google` is one (D67): no build step or packaging entry, readable by the
 * person whose machine it is on, and it re-reads `$HOLI_HOOK_PORT` /
 * `$HOLI_HOOK_TOKEN` at every invocation — so it survives an app restart, which
 * moves the ephemeral port. Baking either in produces a CLI that works exactly
 * until Holi is restarted once, and then fails in a way that looks like a
 * network bug.
 *
 * It exists because slice 1 left the agent writing an app blind: it could not
 * see the result, so its only move was to ask the user to go and look. `app
 * open` closes that loop.
 *
 * `holi-google` sorts its subcommands by reversibility, because some of them
 * reach another person. **All three of these are reversible** — opening a tab,
 * scaffolding a directory, rewriting a file Holi itself wrote and can rewrite
 * again — which is why none of them is gated. That is the same rule (D70)
 * reaching the opposite conclusion, not a different one.
 */
import { chmod, mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const SCRIPT = `#!/bin/sh
# holi — ask the running Holi app to do something.
# Generated by Holi. Talks to the app over 127.0.0.1 and holds no secret of
# yours: the port and the token come from the environment Holi started you with.
#
# Every command here is reversible, which is why none of them asks first:
#   app open <id>            open the app's tab (you can close it)
#   app init <id>            scaffold a new app directory (you can delete it)
#   seed refresh [path]      rewrite the managed files Holi itself wrote
#
# If this says Holi is not running, it is not running, or you are in a shell it
# did not start.
set -eu

if [ -z "\${HOLI_HOOK_PORT:-}" ] || [ -z "\${HOLI_HOOK_TOKEN:-}" ]; then
  echo "holi: Holi is not running, or this shell was not started by it." >&2
  exit 1
fi

base="http://127.0.0.1:\$HOLI_HOOK_PORT"

usage() {
  cat >&2 <<'USAGE'
usage: holi <command>

  app open <id>                 open a finished app in a tab
  app init <id>                 scaffold .holi/apps/<id>/ with a manifest
  seed refresh [path] [--force] rewrite the managed files Holi wrote

An app is finished when it has app.yaml next to index.html. Write the manifest
LAST: it is what registers the app, so the tab never opens onto half a page.
USAGE
  exit 2
}

# POST one operation. The token rides in the query string (one auth mechanism,
# the same one the turn-signal hooks use); every argument rides in the body so
# curl encodes it. Hand-rolling percent-encoding in POSIX sh is how a path with
# a space silently becomes a different path.
post() {
  op="\$1"; shift
  curl -sS --fail-with-body -X POST "\$base/\$op?t=\$HOLI_HOOK_TOKEN" "\$@"
}

cmd="\${1:-}"
[ $# -gt 0 ] && shift

case "\$cmd" in
  app)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      open)
        [ $# -ge 1 ] || { echo "holi app open <id>" >&2; exit 2; }
        post app/open --data-urlencode "id=\$1"
        ;;
      init)
        [ $# -ge 1 ] || { echo "holi app init <id>" >&2; exit 2; }
        post app/init --data-urlencode "id=\$1"
        ;;
      *) usage ;;
    esac
    ;;
  seed)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      refresh)
        # Options are parsed into variables FIRST, then the curl arguments are
        # built: building them with \`set --\` while still looping over \$@
        # rewrites the very list being iterated, and the loop reads its own
        # output. (holi-google reschedule carries the same comment, and the
        # same scar.)
        path=""; force=""
        while [ $# -gt 0 ]; do
          case "\$1" in
            --force) force=true; shift ;;
            -*) echo "holi seed refresh: unknown option \$1" >&2; exit 2 ;;
            *) path="\$1"; shift ;;
          esac
        done
        set -- --data-urlencode "force=\${force:-false}"
        [ -n "\$path" ] && set -- "\$@" --data-urlencode "path=\$path"
        post seed/refresh "\$@"
        ;;
      *) usage ;;
    esac
    ;;
  *) usage ;;
esac
`

/**
 * Write the script and make it executable. Returns its absolute path, which
 * becomes `$HOLI_BIN` in the agent's env.
 *
 * Rewritten on every launch rather than written once: it is generated content,
 * so an app update must not leave an older copy in place.
 */
export async function installHoliCli(userDataDir: string): Promise<string> {
  const path = join(userDataDir, 'bin', 'holi')
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, SCRIPT, { mode: 0o755 })
  // `writeFile`'s mode is ignored when the file already exists.
  await chmod(path, 0o755)
  return path
}

export { SCRIPT as HOLI_CLI_SCRIPT }
