/**
 * `holi` — the command the agent types to ask Holi to do something.
 *
 * A generated shell script rather than a shipped binary, for the reasons
 * `holi-google` is one: no build step or packaging entry, readable by the
 * person whose machine it is on, and it re-reads `$CLAUDE_CONFIG_DIR/holi.env`
 * at every invocation, so it survives an app restart, which moves the ephemeral
 * port.
 *
 * **Every command is reversible or read-only** (opening a tab, scaffolding a
 * directory, merging Holi's newer skills into the vault's, printing PDF
 * comments), which
 * is why none of them is gated. That is the reversibility rule reaching the opposite
 * conclusion from `holi-google send`.
 */
import { chmod, mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const SCRIPT = `#!/bin/sh
# holi — ask the running Holi app to do something.
# Generated by Holi. Talks to the app over 127.0.0.1 and holds no secret of
# yours: the port and the token come from holi.env in your Claude config dir.
#
# Every command here is reversible or read-only, which is why none of them
# asks first:
#   app open <path>          open the app's tab (you can close it)
#   app init <path>          scaffold a new app bundle (you can delete it)
#   skills update            merge this release's skills and hooks into the
#                            vault's (a conflict gets a session of its own)
#   pdf comments <path>      print a PDF's comments (reads, changes nothing)
#
# If this says Holi is not running, it is not running, or you are in a shell it
# did not start.
set -eu

# The port and tokens live in a file in the vault's Claude Code config dir,
# rewritten by Holi each time it opens the vault. A background session's
# environment comes from Claude Code's supervisor, so it cannot carry them.
if [ -n "\${CLAUDE_CONFIG_DIR:-}" ] && [ -f "\$CLAUDE_CONFIG_DIR/holi.env" ]; then
  . "\$CLAUDE_CONFIG_DIR/holi.env"
fi

if [ -z "\${HOLI_HOOK_PORT:-}" ] || [ -z "\${HOLI_HOOK_TOKEN:-}" ]; then
  echo "holi: Holi is not running, or this shell was not started by it." >&2
  exit 1
fi

base="http://127.0.0.1:\$HOLI_HOOK_PORT"

usage() {
  cat >&2 <<'USAGE'
usage: holi <command>

  app open <path>               open a finished app in a tab, or reload it
                                if it is already open
  app init <path>               scaffold <path> (a folder ending in .app)
  skills update                 bring this release's skills and hooks into the
                                vault, merged with its own changes
  pdf comments <path> [--json]  print a vault PDF's comments: page, mark,
                                marked text, author, dates and replies
  task done <path>              complete a task file; a recurring one rolls
                                forward to its next occurrence

An app is a folder ending in .app, anywhere in the vault, e.g. Finance/Budget.app.
It is finished when it has app.yaml next to index.html. Write the manifest LAST:
it is what finishes the app, so the tab never opens onto half a page.
USAGE
  exit 2
}

# POST one operation. The token rides in the query string (one auth mechanism,
# the same one the turn-signal hooks use); every argument rides in the body so
# curl encodes it. Hand-rolling percent-encoding in POSIX sh is how a path with
# a space silently becomes a different path.
post() {
  op="\$1"; shift
  curl -sS --fail-with-body -X POST "\$base/\$op?t=\$HOLI_HOOK_TOKEN" "\$@"
}

cmd="\${1:-}"
[ $# -gt 0 ] && shift

case "\$cmd" in
  app)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      open)
        [ $# -ge 1 ] || { echo "holi app open <path>" >&2; exit 2; }
        post app/open --data-urlencode "path=\$1"
        ;;
      init)
        [ $# -ge 1 ] || { echo "holi app init <path>" >&2; exit 2; }
        post app/init --data-urlencode "path=\$1"
        ;;
      *) usage ;;
    esac
    ;;
  skills)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      update)
        # The answer is one line of text; the status decides where it goes, as
        # for pdf comments below.
        body=\$(mktemp)
        trap 'rm -f "\$body"' EXIT
        code=\$(curl -sS -X POST -o "\$body" -w '%{http_code}' \\
          "\$base/skills/update?t=\$HOLI_HOOK_TOKEN") || exit 1
        if [ "\$code" = 200 ]; then
          cat "\$body"; echo
        else
          echo "holi skills update: \$(cat "\$body")" >&2
          exit 1
        fi
        ;;
      *) usage ;;
    esac
    ;;
  task)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      done)
        [ $# -ge 1 ] || { echo "holi task done <path>" >&2; exit 2; }
        post task/done --data-urlencode "path=\$1"
        ;;
      *) usage ;;
    esac
    ;;
  pdf)
    sub="\${1:-}"
    [ $# -gt 0 ] && shift
    case "\$sub" in
      comments)
        path=""; json=""
        while [ $# -gt 0 ]; do
          case "\$1" in
            --json) json=true; shift ;;
            -*) echo "holi pdf comments: unknown option \$1" >&2; exit 2 ;;
            *) path="\$1"; shift ;;
          esac
        done
        [ -n "\$path" ] || { echo "holi pdf comments <path> [--json]" >&2; exit 2; }
        # Not \`post\`: the answer is the output itself, so the status decides
        # where it goes (stdout, or stderr and a failing exit) rather than
        # curl's exit code. The body goes through a file so that nothing about
        # its contents, a trailing newline included, is lost on the way.
        body=\$(mktemp)
        trap 'rm -f "\$body"' EXIT
        code=\$(curl -sS -X POST -o "\$body" -w '%{http_code}' \\
          "\$base/pdf/comments?t=\$HOLI_HOOK_TOKEN" \\
          --data-urlencode "path=\$path" --data-urlencode "json=\${json:-false}") || exit 1
        if [ "\$code" = 200 ]; then
          cat "\$body"; echo
        else
          echo "holi pdf comments: \$(cat "\$body")" >&2
          exit 1
        fi
        ;;
      *) usage ;;
    esac
    ;;
  *) usage ;;
esac
`

/**
 * Write the script and make it executable. Returns its absolute path, which
 * becomes `$HOLI_BIN` in the agent's env.
 *
 * Rewritten on every launch rather than written once: it is generated content,
 * so an app update must not leave an older copy in place.
 */
export async function installHoliCli(userDataDir: string): Promise<string> {
  const path = join(userDataDir, 'bin', 'holi')
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, SCRIPT, { mode: 0o755 })
  // `writeFile`'s mode is ignored when the file already exists.
  await chmod(path, 0o755)
  // The status-line script earlier versions wrote beside this one. Its
  // setting is removed from each vault's config directory, and a stale
  // copy would still post to a port that no longer answers.
  await rm(join(userDataDir, 'bin', 'holi-statusline'), { force: true })
  return path
}

export { SCRIPT as HOLI_CLI_SCRIPT }
