/**
 * `holi-google` — the command the agent actually types.
 *
 * A generated shell script rather than a shipped binary, for three reasons: it
 * needs no build step or packaging entry, it is readable by the person whose
 * machine it is on, and it re-reads `$HOLI_GOOGLE_PORT`/`$HOLI_GOOGLE_TOKEN` at
 * every invocation — so it keeps working across app restarts that move the port.
 *
 * It is a thin curl wrapper on purpose. All it does is name the operations, so
 * the agent has one documented command instead of a URL to assemble, and so a
 * future write operation can be gated as its own subcommand rather than hiding
 * inside a general-purpose `curl`.
 */
import { chmod, mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

/** The script. `$1` is the subcommand; the rest are its arguments. */
const SCRIPT = `#!/bin/sh
# holi-google — read the signed-in user's Google calendar and mail.
# Generated by Holi. Talks to the app over 127.0.0.1; it never sees a token of
# yours, and it can only read (the granted scopes are readonly).
set -eu

if [ -z "\${HOLI_GOOGLE_PORT:-}" ] || [ -z "\${HOLI_GOOGLE_TOKEN:-}" ]; then
  echo "holi-google: Holi is not running, or Google is not connected." >&2
  exit 1
fi

base="http://127.0.0.1:\$HOLI_GOOGLE_PORT"
cmd="\${1:-}"
[ $# -gt 0 ] && shift

# -G + --data-urlencode makes curl build the query string, so a search like
# 'subject:"Q2 budget" from:a@b.c' survives intact. Hand-rolling percent-encoding
# in POSIX sh is how a quoted query silently becomes a different query.
case "\$cmd" in
  agenda)
    # agenda [fromISO] [toISO] — defaults to the next 7 days.
    set -- \${1:+--data-urlencode "timeMin=\$1"} \${2:+--data-urlencode "timeMax=\$2"}
    curl -sS --fail-with-body -G "\$base/agenda" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" "\$@"
    ;;
  search)
    # search "<gmail query>" — Gmail's own grammar. Empty means the inbox.
    curl -sS --fail-with-body -G "\$base/threads" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" --data-urlencode "q=\${1:-}"
    ;;
  read)
    # read <threadId>
    [ $# -ge 1 ] || { echo "holi-google read <threadId>" >&2; exit 2; }
    curl -sS --fail-with-body -G "\$base/thread" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" --data-urlencode "id=\$1"
    ;;
  *)
    echo "usage: holi-google (agenda [fromISO toISO] | search <query> | read <threadId>)" >&2
    exit 2
    ;;
esac
`

/**
 * Write the script and make it executable. Returns its absolute path, which
 * becomes `$HOLI_GOOGLE_BIN` in the agent's env.
 *
 * Rewritten on every launch rather than written once: it is generated content,
 * so an app update must not leave an older copy in place.
 */
export async function installGoogleCli(userDataDir: string): Promise<string> {
  const path = join(userDataDir, 'bin', 'holi-google')
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, SCRIPT, { mode: 0o755 })
  // `writeFile`'s mode is ignored when the file already exists.
  await chmod(path, 0o755)
  return path
}

export { SCRIPT as GOOGLE_CLI_SCRIPT }
