/**
 * `holi-google` — the command the agent actually types.
 *
 * A generated shell script rather than a shipped binary, for three reasons: it
 * needs no build step or packaging entry, it is readable by the person whose
 * machine it is on, and it re-reads `$HOLI_GOOGLE_PORT`/`$HOLI_GOOGLE_TOKEN` at
 * every invocation — so it keeps working across app restarts that move the port.
 *
 * It is a thin curl wrapper on purpose. All it does is name the operations, so
 * the agent has one documented command instead of a URL to assemble, and so a
 * future write operation can be gated as its own subcommand rather than hiding
 * inside a general-purpose `curl`.
 */
import { chmod, mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

/** The script. `$1` is the subcommand; the rest are its arguments. */
const SCRIPT = `#!/bin/sh
# holi-google — read and act on the signed-in user's Google calendar and mail.
# Generated by Holi. Talks to the app over 127.0.0.1; it never sees a token of
# yours.
#
# What it can do is sorted by whether you can undo it (D70):
#   read      agenda, search, read
#   undoable  mark-read, star, archive, trash, draft, schedule, reschedule,
#             unschedule — every one of these has a one-click undo in Gmail or
#             Google Calendar
#   sends     send, reply — these reach another person and cannot be recalled,
#             so Holi asks the user every single time one is run
#
# Two things are impossible rather than merely gated: permanently deleting mail
# (the scope is not requested and will not be), and touching a calendar event
# that has attendees (Holi refuses, because it would email them).
set -eu

if [ -z "\${HOLI_GOOGLE_PORT:-}" ] || [ -z "\${HOLI_GOOGLE_TOKEN:-}" ]; then
  echo "holi-google: Holi is not running, or Google is not connected." >&2
  exit 1
fi

base="http://127.0.0.1:\$HOLI_GOOGLE_PORT"
cmd="\${1:-}"
[ $# -gt 0 ] && shift

# POST to one operation. The token rides in the query string exactly as it does
# for the reads, so there is one auth mechanism rather than two; everything else
# is a form field curl encodes for us.
post() {
  op="\$1"; shift
  curl -sS --fail-with-body -X POST "\$base/\$op?t=\$HOLI_GOOGLE_TOKEN" "\$@"
}

# -G + --data-urlencode makes curl build the query string, so a search like
# 'subject:"Q2 budget" from:a@b.c' survives intact. Hand-rolling percent-encoding
# in POSIX sh is how a quoted query silently becomes a different query.
case "\$cmd" in
  agenda)
    # agenda [fromISO] [toISO] — defaults to the next 7 days.
    set -- \${1:+--data-urlencode "timeMin=\$1"} \${2:+--data-urlencode "timeMax=\$2"}
    curl -sS --fail-with-body -G "\$base/agenda" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" "\$@"
    ;;
  search)
    # search "<gmail query>" — Gmail's own grammar. Empty means the inbox.
    curl -sS --fail-with-body -G "\$base/threads" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" --data-urlencode "q=\${1:-}"
    ;;
  read)
    # read <threadId>
    [ $# -ge 1 ] || { echo "holi-google read <threadId>" >&2; exit 2; }
    curl -sS --fail-with-body -G "\$base/thread" \\
      --data-urlencode "t=\$HOLI_GOOGLE_TOKEN" --data-urlencode "id=\$1"
    ;;
  # ---- writes -------------------------------------------------------------
  # Every write POSTs a form body. curl does the encoding, including reading the
  # message from stdin with @-, so nothing here hand-escapes a quote, a $ or a
  # newline. Building JSON in POSIX sh is the same class of bug as hand-rolling
  # percent-encoding, and it fails the same way: silently, on the one message
  # that contained a quotation mark.
  mark-read)
    # mark-read <threadId> [--unread]
    [ $# -ge 1 ] || { echo "holi-google mark-read <threadId> [--unread]" >&2; exit 2; }
    read_flag=true
    [ "\${2:-}" = "--unread" ] && read_flag=false
    post mark-read --data-urlencode "id=\$1" --data-urlencode "read=\$read_flag"
    ;;
  star)
    # star <threadId> [--off]
    [ $# -ge 1 ] || { echo "holi-google star <threadId> [--off]" >&2; exit 2; }
    on=true
    [ "\${2:-}" = "--off" ] && on=false
    post star --data-urlencode "id=\$1" --data-urlencode "on=\$on"
    ;;
  archive)
    [ $# -ge 1 ] || { echo "holi-google archive <threadId>" >&2; exit 2; }
    post archive --data-urlencode "id=\$1"
    ;;
  trash)
    # Gmail's trash, recoverable for 30 days. Permanent deletion is impossible.
    [ $# -ge 1 ] || { echo "holi-google trash <threadId>" >&2; exit 2; }
    post trash --data-urlencode "id=\$1"
    ;;
  draft|send)
    # draft --to <addr> --subject <text> [--cc <addr>] [--thread <id>]
    # send  --to <addr> --subject <text> [--cc <addr>]
    # send  --draft <draftId>          <- sends a draft that already exists
    # The message body is read from STDIN, except for send --draft.
    to=""; subject=""; cc=""; thread=""; draft_id=""
    while [ $# -gt 0 ]; do
      case "\$1" in
        --to) to="\$2"; shift 2 ;;
        --subject) subject="\$2"; shift 2 ;;
        --cc) cc="\$2"; shift 2 ;;
        --thread) thread="\$2"; shift 2 ;;
        --draft) draft_id="\$2"; shift 2 ;;
        *) echo "holi-google \$cmd: unknown option \$1" >&2; exit 2 ;;
      esac
    done
    if [ -n "\$draft_id" ]; then
      # A draft already carries its recipients, subject and threading headers,
      # so there is nothing to compose and NOTHING TO READ FROM STDIN — reading
      # it here would block forever on a command with no pipe.
      [ "\$cmd" = send ] || { echo "holi-google draft: --draft is only for send" >&2; exit 2; }
      [ -z "\$to" ] || { echo "holi-google send: --draft and --to are alternatives" >&2; exit 2; }
      post send --data-urlencode "draftId=\$draft_id"
    else
      [ -n "\$to" ] || { echo "holi-google \$cmd --to <addr> --subject <text>  (body on stdin)" >&2; exit 2; }
      set -- --data-urlencode "to=\$to" --data-urlencode "subject=\$subject"
      [ -n "\$cc" ] && set -- "\$@" --data-urlencode "cc=\$cc"
      [ -n "\$thread" ] && set -- "\$@" --data-urlencode "threadId=\$thread"
      # @- is the whole point: curl reads the body from stdin and encodes it.
      post "\$cmd" "\$@" --data-urlencode "body@-"
    fi
    ;;
  reply)
    # reply <threadId> [--all]  — the body is read from STDIN. Recipients and
    # the subject come from the thread, so there is nothing to get wrong here.
    # Without --all this replies to the sender only: the confirmation prompt
    # cannot show a derived recipient list, so it must not silently be everyone.
    [ $# -ge 1 ] || { echo "holi-google reply <threadId> [--all]  (body on stdin)" >&2; exit 2; }
    thread_id="\$1"; shift
    reply_all=""
    while [ $# -gt 0 ]; do
      case "\$1" in
        --all) reply_all=true; shift ;;
        *) echo "holi-google reply: unknown option \$1" >&2; exit 2 ;;
      esac
    done
    set -- --data-urlencode "threadId=\$thread_id"
    [ -n "\$reply_all" ] && set -- "\$@" --data-urlencode "all=true"
    post reply "\$@" --data-urlencode "body@-"
    ;;
  schedule)
    # schedule --title <t> --start <iso> --end <iso> [--all-day] [--location <l>]
    title=""; start=""; end=""; all_day=""; location=""
    while [ $# -gt 0 ]; do
      case "\$1" in
        --title) title="\$2"; shift 2 ;;
        --start) start="\$2"; shift 2 ;;
        --end) end="\$2"; shift 2 ;;
        --location) location="\$2"; shift 2 ;;
        --all-day) all_day=true; shift ;;
        *) echo "holi-google schedule: unknown option \$1" >&2; exit 2 ;;
      esac
    done
    [ -n "\$title" ] && [ -n "\$start" ] && [ -n "\$end" ] || {
      echo "holi-google schedule --title <t> --start <iso> --end <iso> [--all-day]" >&2; exit 2; }
    set -- --data-urlencode "title=\$title" --data-urlencode "start=\$start" \\
      --data-urlencode "end=\$end"
    [ -n "\$all_day" ] && set -- "\$@" --data-urlencode "allDay=true"
    [ -n "\$location" ] && set -- "\$@" --data-urlencode "location=\$location"
    post schedule "\$@"
    ;;
  reschedule)
    # reschedule <eventId> [--start <iso>] [--end <iso>] [--title <t>]
    [ $# -ge 1 ] || { echo "holi-google reschedule <eventId> [--start <iso>] [--end <iso>]" >&2; exit 2; }
    id="\$1"; shift
    # Options are parsed into variables FIRST, then the curl arguments are
    # built. Building them with \`set --\` while still looping over \$@ rewrites
    # the very list being iterated, and the loop then reads its own output.
    start=""; end=""; title=""
    while [ $# -gt 0 ]; do
      case "\$1" in
        --start) start="\$2"; shift 2 ;;
        --end) end="\$2"; shift 2 ;;
        --title) title="\$2"; shift 2 ;;
        *) echo "holi-google reschedule: unknown option \$1" >&2; exit 2 ;;
      esac
    done
    set -- --data-urlencode "id=\$id"
    [ -n "\$start" ] && set -- "\$@" --data-urlencode "start=\$start"
    [ -n "\$end" ] && set -- "\$@" --data-urlencode "end=\$end"
    [ -n "\$title" ] && set -- "\$@" --data-urlencode "title=\$title"
    post reschedule "\$@"
    ;;
  unschedule)
    # Refused by Holi if the event has attendees — deleting it would email them.
    [ $# -ge 1 ] || { echo "holi-google unschedule <eventId>" >&2; exit 2; }
    post unschedule --data-urlencode "id=\$1"
    ;;
  *)
    cat >&2 <<'USAGE'
usage: holi-google <command>

  read
    agenda [fromISO] [toISO]
    search <gmail query>
    read <threadId>

  undoable
    mark-read <threadId> [--unread]
    star <threadId> [--off]
    archive <threadId>
    trash <threadId>
    draft --to <addr> --subject <text> [--cc <addr>] [--thread <id>]   (body on stdin)
    schedule --title <t> --start <iso> --end <iso> [--all-day] [--location <l>]
    reschedule <eventId> [--start <iso>] [--end <iso>] [--title <t>]
    unschedule <eventId>

  reaches another person — Holi asks the user every time
    send --to <addr> --subject <text> [--cc <addr>]   (body on stdin)
    send --draft <draftId>                            (sends an existing draft)
    reply <threadId> [--all]                          (body on stdin)
USAGE
    exit 2
    ;;
esac
`

/**
 * Write the script and make it executable. Returns its absolute path, which
 * becomes `$HOLI_GOOGLE_BIN` in the agent's env.
 *
 * Rewritten on every launch rather than written once: it is generated content,
 * so an app update must not leave an older copy in place.
 */
export async function installGoogleCli(userDataDir: string): Promise<string> {
  const path = join(userDataDir, 'bin', 'holi-google')
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, SCRIPT, { mode: 0o755 })
  // `writeFile`'s mode is ignored when the file already exists.
  await chmod(path, 0o755)
  return path
}

export { SCRIPT as GOOGLE_CLI_SCRIPT }
