/**
 * The vault's memory index — pure (D89).
 *
 * A memory is one fact in one file under `memory/`, carrying a `type`, a
 * one-line `description` and an optional `title`. This module turns a set of
 * those files into `memory/index.md`: sections by type, one line per memory.
 *
 * **It maintains, it never enforces.** Every key is optional in practice: a
 * missing `title` falls back to the H1 then the filename, a missing
 * `description` to the body's first sentence, a missing `type` to `note`, and
 * frontmatter that is not valid YAML is treated exactly as if it were absent.
 * Nothing here can fail, which matters because the caller is a pre-commit
 * transform and `prd/vaults-sync.md` FR-9 says a transform may never block a
 * commit. A half-written memory file must not be able to stop someone saving.
 *
 * **No IO.** Files in, markdown out. The transform is the only thing that
 * touches the disk, which is what lets every rule below be tested without a
 * fixture.
 *
 * The index is committed, so it lists **shared memories only**: a
 * `memory/x.local.md` is personal (D65) and its title and description appear in
 * no committed file anywhere. That is the one rule here with a consequence
 * worse than untidiness, and `isSharedMemoryPath` is where it lives.
 */

import { parse as parseYaml } from 'yaml'
import { MEMORY_DIR, isLocalOnlyPath } from './path-safety'
import { splitFrontmatter } from './task-file'

/** `MEMORY_DIR` itself lives in `path-safety.ts` — `isAgentSurfacePath` needs it
 *  and this module needs `isLocalOnlyPath`, so the constant sits at the lower of
 *  the two. It reaches consumers as `@holi/shared`'s either way. */
export const MEMORY_INDEX = `${MEMORY_DIR}/index.md`

/** The type a memory with no `type` is filed under. */
export const DEFAULT_MEMORY_TYPE = 'note'

/** The header the generated index opens with. Present so that someone who opens
 *  `index.md` to fix a typo is told where the typo actually lives — the next
 *  commit would discard the edit either way, silently, and a generated file
 *  that does not say it is generated is a trap. */
export const MEMORY_INDEX_HEADER = '<!-- Generated by Holi. Edit the memory files, not this. -->'

/** What the index says when the vault has no memories yet. Also what the seed
 *  writes, so `memory/` exists and is tracked from a vault's first commit. */
export const MEMORY_INDEX_EMPTY = `${MEMORY_INDEX_HEADER}

This vault has no memories yet. A memory is one fact in one file under \`memory/\`.
`

/**
 * A memory file: under `memory/`, markdown, and not the generated index itself.
 *
 * A **prefix** match, unlike the exact filenames it sits beside in
 * `path-safety.ts`, because `memory/` is a directory: `notes/memory/x.md` is an
 * ordinary note somebody wrote and is none of this module's business.
 */
export function isMemoryPath(path: string): boolean {
  return path.startsWith(`${MEMORY_DIR}/`) && path.endsWith('.md') && path !== MEMORY_INDEX
}

/** A memory file that is committed rather than personal. The index lists these
 *  and only these — see the module header. */
export function isSharedMemoryPath(path: string): boolean {
  return isMemoryPath(path) && !isLocalOnlyPath(path)
}

export interface MemoryEntry {
  path: string
  /** Frontmatter `type`, else `note`. Free-form on purpose: the session
   *  overview prints the types in use, which lets the vocabulary document and
   *  converge on itself without anyone maintaining a registry. */
  type: string
  /** Frontmatter `title`, else the body's H1, else the filename without `.md`. */
  title: string
  /** Frontmatter `description`, else the body's first sentence, else empty. */
  description: string
}

/** Longest description the index will print. An entry that wraps three times is
 *  an entry nobody reads, and the file itself is one `Read` away. */
const DESCRIPTION_LIMIT = 120

function titleFromPath(path: string): string {
  const base = path.split('/').at(-1) ?? path
  return base.replace(/\.md$/i, '')
}

/** Frontmatter as a plain object. Anything that is not a YAML map — malformed,
 *  a bare scalar, a list — reads as "no frontmatter", never as an error. */
function frontmatterOf(text: string): Record<string, unknown> {
  let yaml: string | null
  try {
    // Throws on an unterminated `---` fence, which is a file mid-edit.
    yaml = splitFrontmatter(text).yaml
  } catch {
    return {}
  }
  if (yaml === null) return {}
  try {
    const parsed: unknown = parseYaml(yaml)
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return {}
    return parsed as Record<string, unknown>
  } catch {
    return {}
  }
}

/** The body, with a leading H1 removed — that H1 is the title, so repeating it
 *  as the description would say the same thing twice on one line. */
function bodyOf(text: string): string {
  let body: string
  try {
    body = splitFrontmatter(text).body
  } catch {
    body = text
  }
  return body.replace(/^\s*#\s+.*(?:\n|$)/, '').trim()
}

function h1Of(text: string): string | null {
  let body: string
  try {
    body = splitFrontmatter(text).body
  } catch {
    body = text
  }
  const match = /^\s*#\s+(.+?)\s*$/m.exec(body)
  return match?.[1] ?? null
}

/** A frontmatter value as a usable string, or null. An empty or
 *  whitespace-only value is a field somebody filled in and then emptied, which
 *  is not an assertion that the memory is nameless — fall through to it. */
function stringValue(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return trimmed === '' ? null : trimmed
}

/** Collapse to one line. Everything this module emits ends up inside a single
 *  markdown list item, where a newline would end the entry early. */
function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}

/**
 * The first sentence of a body, truncated at a word boundary.
 *
 * Deliberately crude: a full stop followed by whitespace or end-of-text. A
 * heuristic that mis-splits `e.g.` costs a slightly long index line, and the
 * alternative is a sentence tokeniser in a package that has no need of one.
 */
function firstSentence(body: string): string {
  const flat = oneLine(body)
  if (flat === '') return ''
  const match = /^(.+?[.!?])(?:\s|$)/.exec(flat)
  return truncate(match?.[1] ?? flat)
}

function truncate(text: string): string {
  if (text.length <= DESCRIPTION_LIMIT) return text
  const cut = text.slice(0, DESCRIPTION_LIMIT)
  const space = cut.lastIndexOf(' ')
  return `${(space > 0 ? cut.slice(0, space) : cut).trimEnd()}…`
}

/**
 * Make a title safe to sit inside `[[path|title]]`.
 *
 * The grammar is `\[\[([^\]\n]+)\]\]` (`wiki-links.ts`) and it has no escape
 * sequence, so this substitutes rather than escapes. Two characters matter, and
 * neither is the one the design notes guessed at:
 *
 * - **`]`** ends the body early, so the whole link stops matching and the reader
 *   gets raw brackets instead of a link. Rendered as `)`, which keeps the
 *   "something closed here" reading.
 * - **A newline** does the same. Collapsed, along with every other whitespace
 *   run, by `oneLine`.
 *
 * A `|` needs nothing: the parser splits on the FIRST pipe and takes the rest of
 * the body as the label, so a piped title arrives intact.
 */
function linkSafe(title: string): string {
  return oneLine(title).replace(/\]/g, ')')
}

export function readMemoryEntry(path: string, text: string): MemoryEntry {
  const frontmatter = frontmatterOf(text)
  const description = stringValue(frontmatter.description)
  return {
    path,
    type: stringValue(frontmatter.type) ?? DEFAULT_MEMORY_TYPE,
    title: stringValue(frontmatter.title) ?? h1Of(text) ?? titleFromPath(path),
    description:
      description !== null ? truncate(oneLine(description)) : firstSentence(bodyOf(text)),
  }
}

/**
 * Entries → the whole of `memory/index.md`.
 *
 * **One sorted line per memory, and that shape is the merge story.** Two members
 * adding different memories on the same afternoon touch different lines in
 * different places, so git merges them without noticing. It is why this design
 * has an index and no `log.md`: a newest-first log is prepended to on every
 * write, so the same two members would conflict on its first lines every single
 * time, in a file no human wrote.
 *
 * Wiki-links rather than OKF's markdown links: one link grammar in the vault, so
 * `relink`, backlinks and the editor's chips all understand these, and the index
 * is clickable in Holi. The bundle is OKF-SHAPED and never claims the label.
 */
export function renderMemoryIndex(entries: MemoryEntry[]): string {
  if (entries.length === 0) return MEMORY_INDEX_EMPTY

  const byType = new Map<string, MemoryEntry[]>()
  for (const entry of entries) {
    const list = byType.get(entry.type)
    if (list === undefined) byType.set(entry.type, [entry])
    else list.push(entry)
  }

  const sections = [...byType.keys()].sort().map((type) => {
    const lines = byType
      .get(type)!
      .slice()
      .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
      .map((entry) => {
        const link = `[[${entry.path}|${linkSafe(entry.title)}]]`
        return entry.description === '' ? `- ${link}` : `- ${link} — ${oneLine(entry.description)}`
      })
    return `## ${type}\n\n${lines.join('\n')}\n`
  })

  return `${MEMORY_INDEX_HEADER}\n\n${sections.join('\n')}`
}
