/**
 * The PreToolUse guard on `memory/index.md`, driven as a real process.
 *
 * The index is regenerated by the memory-index transform on every commit, so an
 * edit to it is always lost. Refusing it up front tells the agent why, where the
 * transform would discard it silently.
 */
import { spawn } from 'node:child_process'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const HOOK = fileURLToPath(
  new URL('../src/main/agent/seed/vault/shipped/.claude/hooks/memory-index-guard.mjs', import.meta.url),
)
const ROOT = '/vaults/o/r'

/** Bare `node` is broken in this environment, so spawn the running interpreter. */
function runHook(payload: unknown): Promise<{ stdout: string; code: number | null }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [HOOK], {
      env: { PATH: process.env.PATH ?? '', CLAUDE_PROJECT_DIR: ROOT },
    })
    let stdout = ''
    child.stdout.on('data', (d: Buffer) => (stdout += d.toString('utf8')))
    child.on('error', reject)
    child.on('close', (code) => resolve({ stdout, code }))
    child.stdin.end(JSON.stringify(payload))
  })
}

describe('memory-index-guard', () => {
  it.each(['Write', 'Edit', 'MultiEdit'])('denies a %s to memory/index.md', async (tool) => {
    const run = await runHook({
      tool_name: tool,
      tool_input: { file_path: join(ROOT, 'memory/index.md') },
    })
    expect(run.code).toBe(0)
    const out = JSON.parse(run.stdout).hookSpecificOutput
    expect(out.permissionDecision).toBe('deny')
    expect(out.permissionDecisionReason).toMatch(/generated/)
  })

  it('says nothing about any other file, memories included', async () => {
    for (const rel of ['memory/people.md', 'notes/memory/index.md', 'index.md']) {
      const run = await runHook({ tool_name: 'Write', tool_input: { file_path: join(ROOT, rel) } })
      expect(run).toEqual({ stdout: '', code: 0 })
    }
  })

  it('says nothing when the payload is not a file write', async () => {
    expect(await runHook({ tool_name: 'Write', tool_input: {} })).toEqual({ stdout: '', code: 0 })
  })
})
