/**
 * The session overview (D89) — run as a real child process, the way Claude Code
 * invokes it.
 *
 * In-process assertions on its helpers would miss the things that actually break
 * a `SessionStart` hook: a non-zero exit, an import Claude Code's node cannot
 * resolve, or a `git` call that hangs in a repo it did not expect. So this
 * spawns the file.
 *
 * Every test asserts `code === 0`. A hook that fails is a session that starts
 * with an error in the transcript, and there is nothing here worth that: the
 * whole feature is an overview the agent could have read for itself.
 */
import { spawn } from 'node:child_process'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it } from 'vitest'

const HOOK = join(
  dirname(fileURLToPath(import.meta.url)),
  '../src/main/agent/hooks/memory-overview.mjs',
)

const roots: string[] = []
afterEach(async () => {
  await Promise.all(roots.splice(0).map((r) => rm(r, { recursive: true, force: true })))
})

async function vault(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'holi-memory-overview-'))
  roots.push(root)
  for (const [rel, text] of Object.entries(files)) {
    await mkdir(join(root, rel, '..'), { recursive: true })
    await writeFile(join(root, rel), text, 'utf8')
  }
  return root
}

/** Spawn the hook with `CLAUDE_PROJECT_DIR` set, as Claude Code does. `cwd` is
 *  kept separate because it must exist for `spawn` itself to succeed — that is
 *  the harness's constraint, not the hook's. */
async function run(root: string, cwd = root): Promise<{ out: string; code: number }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [HOOK], {
      env: { ...process.env, CLAUDE_PROJECT_DIR: root },
      cwd,
    })
    let out = ''
    child.stdout.on('data', (c: Buffer) => (out += c.toString('utf8')))
    child.on('error', reject)
    child.on('close', (code) => resolve({ out, code: code ?? 0 }))
  })
}

const INDEX = `<!-- Generated by Holi. Edit the memory files, not this. -->

## convention

- [[memory/plan-style.md|Plan style]] — plans carry contracts, never inline code
- [[memory/commits.md|Commit style]] — one change, one commit

## environment

- [[memory/shell.md|Shell quirks]] — bare node and npx are broken
`

describe('memory-overview', () => {
  it('prints nothing at all in a directory with no memory', async () => {
    // The ordinary case for a repo somebody opened `claude` in by hand, and the
    // same thing the focused-note hook does outside Holi.
    const { out, code } = await run(await vault({ 'notes/plan.md': '# Plan\n' }))
    expect(out).toBe('')
    expect(code).toBe(0)
  })

  it('counts the types in use, from the index it was handed', async () => {
    // Free-form types are made self-documenting by being counted here, which is
    // why there is no registry to maintain.
    const { out, code } = await run(await vault({ 'memory/index.md': INDEX }))
    expect(code).toBe(0)
    expect(out).toContain('Types in use: convention (2), environment (1)')
  })

  it('reproduces the index lines verbatim, so the hook parses nothing twice', async () => {
    const { out } = await run(await vault({ 'memory/index.md': INDEX }))
    expect(out).toContain('- [[memory/plan-style.md|Plan style]] — plans carry contracts')
    expect(out).toContain('## environment')
  })

  it('includes personal memories, which appear in no committed file', async () => {
    // The overview is the ONLY reader a `.local.md` memory has: it is excluded
    // from the committed index by design (D65), and `index.local.md` was
    // deliberately not built.
    const { out } = await run(
      await vault({
        'memory/index.md': INDEX,
        'memory/salary.local.md':
          '---\ntype: person\ntitle: Pay review\ndescription: due in March\n---\n\nThe fact.\n',
      }),
    )
    expect(out).toContain('personal')
    expect(out).toContain('[[memory/salary.local.md|Pay review]] — due in March')
  })

  it('runs on a personal memory alone, with no index at all', async () => {
    const { out, code } = await run(
      await vault({ 'memory/mine.local.md': '# Mine\n\nA private fact.\n' }),
    )
    expect(code).toBe(0)
    expect(out).toContain('[[memory/mine.local.md|Mine]]')
  })

  it('says so when memories exist but no index has been generated', async () => {
    // A vault whose `memory/` was filled in outside Holi, or one whose index was
    // deleted. Printing nothing would tell the agent the vault remembers nothing
    // — the exact silent failure this hook exists to prevent.
    const { out, code } = await run(
      await vault({
        'memory/a.md': '---\ntype: convention\ndescription: the first\n---\n\nA fact.\n',
        'memory/b.md': '---\ntype: convention\ndescription: the second\n---\n\nAnother.\n',
      }),
    )
    expect(code).toBe(0)
    expect(out).toContain('2 shared')
    expect(out).toContain('has not been generated yet')
  })

  it('offers to split a legacy MEMORY.md that has something in it', async () => {
    const { out } = await run(
      await vault({ 'memory/index.md': INDEX, 'MEMORY.md': '# Memory\n\nWe use pnpm.\n' }),
    )
    expect(out).toMatch(/legacy `MEMORY\.md`/)
  })

  it('says nothing about an empty MEMORY.md, which is the old seed’s leftover', async () => {
    const { out } = await run(await vault({ 'memory/index.md': INDEX, 'MEMORY.md': '\n' }))
    expect(out).not.toMatch(/legacy/)
  })

  it('survives a directory that is not a git repository', async () => {
    // `git log` fails outright here. Every failure is swallowed: a vault
    // mid-rebase, or a `memory/` with no commits yet, prints the rest.
    const { out, code } = await run(await vault({ 'memory/index.md': INDEX }))
    expect(code).toBe(0)
    expect(out).toContain('Types in use')
    expect(out).not.toContain('## recent')
  })

  it('stays under the cap, dropping descriptions before titles', async () => {
    // A title the agent cannot see is a memory it will never Read, so cutting
    // names to save room would defeat the section this exists to print.
    const many = [
      '<!-- Generated by Holi. Edit the memory files, not this. -->',
      '',
      '## convention',
      '',
      ...Array.from(
        { length: 120 },
        (_, i) => `- [[memory/m${i}.md|Memory number ${i}]] — ${'a long description '.repeat(4)}`,
      ),
    ].join('\n')

    const { out, code } = await run(await vault({ 'memory/index.md': `${many}\n` }))

    expect(code).toBe(0)
    expect(out.length).toBeLessThanOrEqual(3000)
    expect(out).toContain('Memory number 0')
    expect(out).not.toContain('a long description')
  })

  it('keeps a whole title when it drops descriptions, even one with an em dash', async () => {
    // Cutting at the first em dash would take half the title with the
    // description, and a half-named memory is one the agent cannot ask for.
    const many = [
      '<!-- Generated by Holi. Edit the memory files, not this. -->',
      '',
      '## convention',
      '',
      ...Array.from(
        { length: 120 },
        (_, i) => `- [[memory/m${i}.md|Number ${i} — the long name]] — ${'padding '.repeat(6)}`,
      ),
    ].join('\n')

    const { out } = await run(await vault({ 'memory/index.md': `${many}\n` }))

    expect(out).toContain('[[memory/m0.md|Number 0 — the long name]]')
    expect(out).not.toContain('padding')
  })

  it('exits 0 and prints nothing when CLAUDE_PROJECT_DIR points nowhere', async () => {
    const real = await vault({})
    const { out, code } = await run(join(tmpdir(), 'holi-does-not-exist-at-all'), real)
    expect(code).toBe(0)
    expect(out).toBe('')
  })
})
